"""Supply the seeds GROMACS draws from the clock, without touching either asset.

`docs/adr/0001` records the measurement this module exists for: `gmx genion` places ions
by replacing randomly chosen solvent molecules, PRISM passes no `-seed`, and two builds
of the same system therefore differ in where every ion sits. A stage wrapping that work
cannot honestly declare itself reproducible, and MolCascade would cache it anyway --
`_cacheable` checks that a seed is *present* in a stage's config, never that the plugin
consumed it.

The obvious fix is to patch PRISM. That is rejected. The assets are vendored at an exact
commit and verified by a digest over every file, so a patch would break the one check that
proves an asset is what it claims to be, and would have to be re-applied on every refresh.
Worse, it would mean ETALON's measurements were taken against a PRISM that exists nowhere
else.

So the seed is supplied from outside. ETALON writes a `gmx` shim into a directory it owns
and puts that directory first on the worker's `PATH`. The shim reads `argv` and does exactly
one thing: an unseeded `genion` is re-executed with `-seed` inserted. **Every other command,
including a `genion` that already carries a seed, is executed with its arguments untouched.**
PRISM is not edited, not read, and not aware of it.

That asymmetry is the whole design and it is what the tests protect. A shim that did more
than this would be a modification of PRISM's behaviour wearing a different hat.

Two further notes on scope.

This module does not decide the seed. It receives one, because a seed that this module
invented would be ETALON's secret rather than part of the record; the caller derives it from
the stage's own seed and records it in the job record beside the shim digest.

This module does not touch MDP files. Velocity generation is a property of a run rather than
of a build -- `gen_vel = yes` with `gen_seed = -1` is read by `mdrun`, not by the build -- so
it belongs to whoever owns run parameters such as `-maxh`, which is the supervisor.
"""

from __future__ import annotations

import hashlib
import os
import shutil
import stat
from dataclasses import dataclass
from pathlib import Path

#: The environment variable the shim reads. Named rather than baked in so that one shim
#: directory serves every job on the host: the seed travels with the process, not with
#: the file, and two concurrent builds with different seeds cannot collide.
SEED_VARIABLE = "ETALON_GENION_SEED"

#: Written as text rather than assembled at call time so that the bytes on disk are the
#: bytes the digest covers and the bytes a person can read. The quoting matters: "$@"
#: preserves arguments containing spaces, which GROMACS paths do.
_SHIM = """\
#!/usr/bin/env bash
# ETALON determinism shim -- see docs/adr/0001-a-build-is-not-a-pure-function.md
#
# Generated by src/etalon/boundary/toolchain.py. Do not edit: the digest of this file is
# recorded in every job record that ran through it, so an edit makes those records wrong
# rather than making this file better.
#
# One behaviour: an unseeded `genion` gets a seed. Everything else passes through with its
# arguments untouched, because the property being protected is that PRISM behaves exactly
# as it does upstream in every other respect.
set -euo pipefail
REAL={real!r}

if [ "${{1:-}}" = "genion" ]; then
  for argument in "$@"; do
    if [ "$argument" = "-seed" ]; then
      exec "$REAL" "$@"
    fi
  done
  if [ -z "${{{seed_variable}:-}}" ]; then
    echo "etalon: {seed_variable} is not set and genion was called without -seed." >&2
    echo "etalon: refusing to let ion placement come from the clock. See ADR 0001." >&2
    exit 64
  fi
  shift
  exec "$REAL" genion -seed "${{{seed_variable}}}" "$@"
fi

exec "$REAL" "$@"
"""


@dataclass(frozen=True, slots=True)
class Toolchain:
    """Where the shim is, what it wraps, and the digest that identifies it.

    The digest is the point. A job record carrying it can answer "which bytes produced
    this number" down to the wrapper that supplied the seed, which is otherwise the one
    link in the chain that leaves no trace.
    """

    shim_dir: Path
    real_gmx: Path
    shim_sha256: str

    def environment(self, *, seed: int, base: dict[str, str] | None = None) -> dict[str, str]:
        """An environment with the shim first on PATH and the seed supplied.

        ``base`` defaults to the current environment rather than to an empty one: a GROMACS
        installation needs ``GMXLIB``, ``LD_LIBRARY_PATH`` and the rest, and a build needs
        the AmberTools that sit beside them. Starting empty would be cleaner in principle
        and would not run.
        """

        environment = dict(os.environ if base is None else base)
        existing = environment.get("PATH", "")
        environment["PATH"] = f"{self.shim_dir}{os.pathsep}{existing}" if existing else str(self.shim_dir)
        environment[SEED_VARIABLE] = str(seed)
        return environment

    def provenance(self) -> dict[str, object]:
        """What a job record should carry about this toolchain."""

        return {
            "shim_dir": str(self.shim_dir),
            "shim_sha256": self.shim_sha256,
            "real_gmx": str(self.real_gmx),
            "seed_variable": SEED_VARIABLE,
            "wraps": ["genion"],
            "passthrough": "every other command, and a genion that already carries -seed",
        }


class ToolchainError(RuntimeError):
    """The shim could not be established, with the reason a caller can act on."""


def locate_gmx(candidates: tuple[str, ...] = ("gmx", "gmx_mpi")) -> Path:
    """The real GROMACS binary, refusing one of ETALON's own shims.

    The refusal is not hypothetical: a shim directory left on ``PATH`` from an earlier run
    would otherwise be found here and wrapped again, and a shim that execs a shim is a loop
    whose symptom is a process that never starts.
    """

    for name in candidates:
        found = shutil.which(name)
        if found is None:
            continue
        path = Path(found).resolve()
        try:
            head = path.read_bytes()[:400]
        except OSError:
            head = b""
        if b"ETALON determinism shim" in head:
            continue
        return path
    raise ToolchainError(
        "no real GROMACS binary on PATH. Source its GMXRC or add its bin directory, and "
        "make sure an ETALON shim directory from an earlier run is not shadowing it."
    )


def install(shim_dir: Path, *, real_gmx: Path | None = None) -> Toolchain:
    """Write the shim into ``shim_dir`` and return what a job record needs about it.

    Idempotent by content: the file is rewritten every call and the digest is recomputed
    from what landed on disk, so a stale shim from an older ETALON cannot survive and be
    reported as the current one.
    """

    binary = (real_gmx or locate_gmx()).resolve()
    if not binary.is_file():
        raise ToolchainError(f"the named GROMACS binary does not exist: {binary}")

    shim_dir = shim_dir.resolve()
    shim_dir.mkdir(parents=True, exist_ok=True)
    target = shim_dir / "gmx"
    if target.is_symlink():
        # A symlink here would make the digest describe something other than what runs.
        raise ToolchainError(f"refusing to overwrite a symlink at {target}")

    contents = _SHIM.format(real=str(binary), seed_variable=SEED_VARIABLE)
    target.write_text(contents, encoding="utf-8")
    target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    written = target.read_bytes()
    return Toolchain(
        shim_dir=shim_dir,
        real_gmx=binary,
        shim_sha256=hashlib.sha256(written).hexdigest(),
    )


def active(environment: dict[str, str] | None = None) -> bool:
    """Whether a shim is first on PATH in the given environment.

    The build plugin calls this to choose what determinism it declares: ``SEEDED`` when a
    shim is supplying the seed, ``NON_DETERMINISTIC`` when nothing is. Declaring ``SEEDED``
    with a seed in the config and no shim on the path is the silent lie ADR 0001 exists to
    prevent, so this is the check that stands between a well-meant config change and a
    cache entry that asserts something false.
    """

    path = (environment or dict(os.environ)).get("PATH", "")
    for directory in path.split(os.pathsep):
        if not directory:
            continue
        candidate = Path(directory) / "gmx"
        if not candidate.is_file():
            continue
        try:
            return b"ETALON determinism shim" in candidate.read_bytes()[:400]
        except OSError:
            return False
    return False


__all__ = [
    "SEED_VARIABLE",
    "Toolchain",
    "ToolchainError",
    "active",
    "install",
    "locate_gmx",
]
